// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Study_Reactis_v1.Entites;

namespace Study_Reactis_v1.Migrations
{
    [DbContext(typeof(DbStudyReactContext))]
    [Migration("20191211093749_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Study_Reactis_v1.Entites.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime?>("Birthday");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Gender");

                    b.Property<string>("Image");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("WorkPlace");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cổ Nhuế 2- Hà Nội",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh.tran@ntq-solution.com.vn",
                            FullName = "Trần Đức Mạnh 1",
                            Gender = "Male",
                            Image = "\\Images\\user5.jpg",
                            PhoneNumber = "0358942987",
                            WorkPlace = "Đang làm việc tại Ntq-solution, khu đô thị Sông Đà."
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cổ Nhuế 2- Hà Nội",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh.tran@ntq-solution.com.vn",
                            FullName = "Trần Đức Mạnh 2",
                            Gender = "Male",
                            Image = "\\Images\\user5.jpg",
                            PhoneNumber = "0358942987",
                            WorkPlace = "Đang làm việc tại Ntq-solution, khu đô thị Sông Đà."
                        },
                        new
                        {
                            Id = 3,
                            Address = "Cổ Nhuế 2- Hà Nội",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh.tran@ntq-solution.com.vn",
                            FullName = "Trần Đức Mạnh 3",
                            Gender = "Male",
                            Image = "\\Images\\user5.jpg",
                            PhoneNumber = "0358942987",
                            WorkPlace = "Đang làm việc tại Ntq-solution, khu đô thị Sông Đà."
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cổ Nhuế 2- Hà Nội",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh.tran@ntq-solution.com.vn",
                            FullName = "Trần Đức Mạnh 4",
                            Gender = "Male",
                            Image = "\\Images\\user5.jpg",
                            PhoneNumber = "0358942987",
                            WorkPlace = "Đang làm việc tại Ntq-solution, khu đô thị Sông Đà."
                        },
                        new
                        {
                            Id = 5,
                            Address = "Cổ Nhuế 2- Hà Nội",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh.tran@ntq-solution.com.vn",
                            FullName = "Trần Đức Mạnh 5",
                            Gender = "Male",
                            Image = "\\Images\\user5.jpg",
                            PhoneNumber = "0358942987",
                            WorkPlace = "Đang làm việc tại Ntq-solution, khu đô thị Sông Đà."
                        },
                        new
                        {
                            Id = 6,
                            Address = "Cổ Nhuế 2- Hà Nội",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh.tran@ntq-solution.com.vn",
                            FullName = "Trần Đức Mạnh 6",
                            Gender = "Male",
                            Image = "\\Images\\user5.jpg",
                            PhoneNumber = "0358942987",
                            WorkPlace = "Đang làm việc tại Ntq-solution, khu đô thị Sông Đà."
                        },
                        new
                        {
                            Id = 7,
                            Address = "Cổ Nhuế 2- Hà Nội",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh.tran@ntq-solution.com.vn",
                            FullName = "Trần Đức Mạnh 7",
                            Gender = "Male",
                            Image = "\\Images\\user5.jpg",
                            PhoneNumber = "0358942987",
                            WorkPlace = "Đang làm việc tại Ntq-solution, khu đô thị Sông Đà."
                        },
                        new
                        {
                            Id = 8,
                            Address = "Cổ Nhuế 2- Hà Nội",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh.tran@ntq-solution.com.vn",
                            FullName = "Trần Đức Mạnh 8",
                            Gender = "Male",
                            Image = "\\Images\\user5.jpg",
                            PhoneNumber = "0358942987",
                            WorkPlace = "Đang làm việc tại Ntq-solution, khu đô thị Sông Đà."
                        },
                        new
                        {
                            Id = 9,
                            Address = "Cổ Nhuế 2- Hà Nội",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh.tran@ntq-solution.com.vn",
                            FullName = "Trần Đức Mạnh 9",
                            Gender = "Male",
                            Image = "\\Images\\user5.jpg",
                            PhoneNumber = "0358942987",
                            WorkPlace = "Đang làm việc tại Ntq-solution, khu đô thị Sông Đà."
                        },
                        new
                        {
                            Id = 10,
                            Address = "Cổ Nhuế 2- Hà Nội",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manh.tran@ntq-solution.com.vn",
                            FullName = "Trần Đức Mạnh 10",
                            Gender = "Male",
                            Image = "\\Images\\user5.jpg",
                            PhoneNumber = "0358942987",
                            WorkPlace = "Đang làm việc tại Ntq-solution, khu đô thị Sông Đà."
                        });
                });

            modelBuilder.Entity("Study_Reactis_v1.Entites.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.Property<string>("UserRole");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "manhtran01",
                            UserName = "manhtran01",
                            UserRole = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Password = "manhtran02",
                            UserName = "manhtran02",
                            UserRole = "user"
                        },
                        new
                        {
                            UserId = 3,
                            Password = "manhtran02",
                            UserName = "manhtran03",
                            UserRole = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
